### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by Pharap** [MrBlinky/Arduboy#2]
I've forked this and added some things that I would class as improvements.
Rather than bundling them all together in a single PR, I'm making an issue to ask which of these improvements (if any) are you interested in incorporating:

https://github.com/Pharap/Arduboy-1/commits/improvements

**Comment by MrBlinky** [comment]
Thanks. I'll go over them and comment

**Comment by Pharap** [comment]
I've read your comments and replied where relevant.

If you'd like me to split my commits up into separate PRs I'm happy to do so.
Otherwise I can apply the fix to that one tiny mistake and make a PR for all the commits.

**Comment by MrBlinky** [comment]
Thanks. Single PR will be fine.
